# Generated by Django 4.1.2 on 2022-11-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Line_Bot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school_exam",
            name="school",
        ),
        migrations.AddField(
            model_name="school_exam",
            name="school_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name="School_name",
        ),
    ]
