# Generated by Django 4.1.2 on 2022-11-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Line_Bot", "0002_remove_school_exam_school_school_exam_school_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school_exam",
            name="year",
        ),
    ]
